version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.5.3
    ports:
      - '9200:9200'
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:8.5.3
    ports:
      - '5601:5601'
    networks:
      - elastic

networks:
  elastic:
    driver: bridge